service: serverless-stations

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  stage: dev
  region: eu-central-1
  runtime: nodejs8.10

functions:
  index:
    handler: handler.index
    events:
      - http:
          path: "/"
          method: get
